CREATE TABLE locks (
  resource_id VARCHAR(255) NOT NULL PRIMARY KEY,
  nonce VARCHAR(255) NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE tenants (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::BIGINT),
  per_day_limit INT NOT NULL,
  tokens INT NOT NULL DEFAULT 100
);
